<?php

namespace Database\Seeders;

use App\Models\Localidade\Pais;
use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    private array $paises = [
        [
            'id' => '4',
            'nome' => 'Afeganistão',
            'nacionalidade' => 'Afegã',
            'ddi' => '93',
        ],
        [
            'id' => '8',
            'nome' => 'Albânia',
            'nacionalidade' => 'Albanesa',
            'ddi' => '355',
        ],
        [
            'id' => '10',
            'nome' => 'Antártida',
            'nacionalidade' => 'Antartida',
            'ddi' => null,
        ],
        [
            'id' => '12',
            'nome' => 'Argélia',
            'nacionalidade' => 'Argelina',
            'ddi' => '213',
        ],
        [
            'id' => '16',
            'nome' => 'Samoa Americana',
            'nacionalidade' => 'Samoana',
            'ddi' => null,
        ],
        [
            'id' => '20',
            'nome' => 'Andorra',
            'nacionalidade' => 'Andorrana',
            'ddi' => '376',
        ],
        [
            'id' => '24',
            'nome' => 'Angola',
            'nacionalidade' => 'Angolana',
            'ddi' => '244',
        ],
        [
            'id' => '28',
            'nome' => 'Antígua e Barbuda',
            'nacionalidade' => 'Antiguana',
            'ddi' => null,
        ],
        [
            'id' => '31',
            'nome' => 'Azerbaijão',
            'nacionalidade' => 'Azerbaijana',
            'ddi' => '994',
        ],
        [
            'id' => '32',
            'nome' => 'Argentina',
            'nacionalidade' => 'Argentina',
            'ddi' => '54',
        ],
        [
            'id' => '36',
            'nome' => 'Austrália',
            'nacionalidade' => 'Australiana',
            'ddi' => '61',
        ],
        [
            'id' => '40',
            'nome' => 'Áustria',
            'nacionalidade' => 'Austríaca',
            'ddi' => '43',
        ],
        [
            'id' => '44',
            'nome' => 'Bahamas',
            'nacionalidade' => 'Baamiana',
            'ddi' => null,
        ],
        [
            'id' => '48',
            'nome' => 'Bahrein',
            'nacionalidade' => 'Baremita',
            'ddi' => '973',
        ],
        [
            'id' => '50',
            'nome' => 'Bangladesh',
            'nacionalidade' => 'Bengali',
            'ddi' => '880',
        ],
        [
            'id' => '51',
            'nome' => 'Armênia',
            'nacionalidade' => 'Arménia',
            'ddi' => '374',
        ],
        [
            'id' => '52',
            'nome' => 'Barbados',
            'nacionalidade' => 'Barbadiana',
            'ddi' => null,
        ],
        [
            'id' => '56',
            'nome' => 'Bélgica',
            'nacionalidade' => 'Belga',
            'ddi' => '32',
        ],
        [
            'id' => '60',
            'nome' => 'Bermudas',
            'nacionalidade' => 'Bermudenha',
            'ddi' => null,
        ],
        [
            'id' => '64',
            'nome' => 'Butão',
            'nacionalidade' => 'Butanesa',
            'ddi' => '975',
        ],
        [
            'id' => '68',
            'nome' => 'Bolívia',
            'nacionalidade' => 'Boliviana',
            'ddi' => '591',
        ],
        [
            'id' => '70',
            'nome' => 'Bósnia e Herzegovina',
            'nacionalidade' => 'Bosnia',
            'ddi' => null,
        ],
        [
            'id' => '72',
            'nome' => 'Botswana',
            'nacionalidade' => 'Botsuana',
            'ddi' => null,
        ],
        [
            'id' => '74',
            'nome' => 'Ilha Bouvet',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '76',
            'nome' => 'Brasil',
            'nacionalidade' => 'Brasileira',
            'ddi' => '55',
        ],
        [
            'id' => '84',
            'nome' => 'Belize',
            'nacionalidade' => 'Belizenha',
            'ddi' => '501',
        ],
        [
            'id' => '86',
            'nome' => 'Território Britânico do Oceano Índico',
            'nacionalidade' => null,
            'ddi' => '246',
        ],
        [
            'id' => '90',
            'nome' => 'Ilhas Salomão',
            'nacionalidade' => 'Salomônica',
            'ddi' => '677',
        ],
        [
            'id' => '92',
            'nome' => 'Ilhas Virgens Britânicas',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '96',
            'nome' => 'Brunei',
            'nacionalidade' => 'Bruneana',
            'ddi' => '673',
        ],
        [
            'id' => '100',
            'nome' => 'Bulgária',
            'nacionalidade' => 'Búlgara',
            'ddi' => '359',
        ],
        [
            'id' => '104',
            'nome' => 'Myanmar',
            'nacionalidade' => 'Birmanesa',
            'ddi' => null,
        ],
        [
            'id' => '108',
            'nome' => 'Burundi',
            'nacionalidade' => 'Burundiana',
            'ddi' => '257',
        ],
        [
            'id' => '112',
            'nome' => 'Bielorrússia',
            'nacionalidade' => 'Bielorrussa',
            'ddi' => null,
        ],
        [
            'id' => '116',
            'nome' => 'Camboja',
            'nacionalidade' => 'Cambojana',
            'ddi' => null,
        ],
        [
            'id' => '120',
            'nome' => 'Camarões',
            'nacionalidade' => 'Camaronesa',
            'ddi' => '237',
        ],
        [
            'id' => '124',
            'nome' => 'Canadá',
            'nacionalidade' => 'Canadense',
            'ddi' => '1',
        ],
        [
            'id' => '132',
            'nome' => 'Cabo Verde',
            'nacionalidade' => 'Cabo-verdiana',
            'ddi' => '238',
        ],
        [
            'id' => '136',
            'nome' => 'Ilhas Cayman',
            'nacionalidade' => 'Caimanesa',
            'ddi' => null,
        ],
        [
            'id' => '140',
            'nome' => 'República Centro-Africana',
            'nacionalidade' => 'Centrafricano',
            'ddi' => '236',
        ],
        [
            'id' => '144',
            'nome' => 'Sri Lanka',
            'nacionalidade' => 'Cingalesa',
            'ddi' => null,
        ],
        [
            'id' => '148',
            'nome' => 'Chade',
            'nacionalidade' => 'Chadiense',
            'ddi' => '235',
        ],
        [
            'id' => '152',
            'nome' => 'Chile',
            'nacionalidade' => 'Chilena',
            'ddi' => '56',
        ],
        [
            'id' => '156',
            'nome' => 'China',
            'nacionalidade' => 'Chinesa',
            'ddi' => '86',
        ],
        [
            'id' => '158',
            'nome' => 'República da China',
            'nacionalidade' => 'Chinesa',
            'ddi' => null,
        ],
        [
            'id' => '162',
            'nome' => 'Ilhas Natal',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '166',
            'nome' => 'Ilhas Cocos (Keeling)',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '170',
            'nome' => 'Colômbia',
            'nacionalidade' => 'Colombiana',
            'ddi' => '57',
        ],
        [
            'id' => '174',
            'nome' => 'Comores',
            'nacionalidade' => 'Comorense',
            'ddi' => null,
        ],
        [
            'id' => '175',
            'nome' => 'Mayotte',
            'nacionalidade' => 'Maiotense',
            'ddi' => '262',
        ],
        [
            'id' => '178',
            'nome' => 'República do Congo',
            'nacionalidade' => 'Congolesa',
            'ddi' => null,
        ],
        [
            'id' => '180',
            'nome' => 'República Democrática do Congo',
            'nacionalidade' => 'Congolesa',
            'ddi' => null,
        ],
        [
            'id' => '184',
            'nome' => 'Ilhas Cook',
            'nacionalidade' => 'Cookense',
            'ddi' => '682',
        ],
        [
            'id' => '188',
            'nome' => 'Costa Rica',
            'nacionalidade' => 'Costa-riquenha',
            'ddi' => '506',
        ],
        [
            'id' => '191',
            'nome' => 'Croácia',
            'nacionalidade' => 'Croata',
            'ddi' => '385',
        ],
        [
            'id' => '192',
            'nome' => 'Cuba',
            'nacionalidade' => 'Cubana',
            'ddi' => '53',
        ],
        [
            'id' => '196',
            'nome' => 'Chipre',
            'nacionalidade' => 'Cipriota',
            'ddi' => null,
        ],
        [
            'id' => '203',
            'nome' => 'República Tcheca',
            'nacionalidade' => 'Tcheca',
            'ddi' => '420',
        ],
        [
            'id' => '204',
            'nome' => 'Benim',
            'nacionalidade' => 'Beninense',
            'ddi' => null,
        ],
        [
            'id' => '208',
            'nome' => 'Dinamarca',
            'nacionalidade' => 'Dinamarquesa',
            'ddi' => '45',
        ],
        [
            'id' => '212',
            'nome' => 'Dominica',
            'nacionalidade' => 'Dominiquesa',
            'ddi' => null,
        ],
        [
            'id' => '214',
            'nome' => 'República Dominicana',
            'nacionalidade' => 'Dominicana',
            'ddi' => null,
        ],
        [
            'id' => '218',
            'nome' => 'Equador',
            'nacionalidade' => 'Equatoriana',
            'ddi' => '593',
        ],
        [
            'id' => '222',
            'nome' => 'El Salvador',
            'nacionalidade' => 'Salvadorenha',
            'ddi' => null,
        ],
        [
            'id' => '226',
            'nome' => 'Guiné Equatorial',
            'nacionalidade' => 'Guinéu-equatoriana',
            'ddi' => '240',
        ],
        [
            'id' => '231',
            'nome' => 'Etiópia',
            'nacionalidade' => 'Etíope',
            'ddi' => '251',
        ],
        [
            'id' => '232',
            'nome' => 'Eritreia',
            'nacionalidade' => 'Eritreu',
            'ddi' => '291',
        ],
        [
            'id' => '233',
            'nome' => 'Estônia',
            'nacionalidade' => 'Estoniana',
            'ddi' => '372',
        ],
        [
            'id' => '234',
            'nome' => 'Ilhas Feroe',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '238',
            'nome' => 'Ilhas Malvinas',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '239',
            'nome' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '242',
            'nome' => 'Fiji',
            'nacionalidade' => 'Fjiana',
            'ddi' => null,
        ],
        [
            'id' => '246',
            'nome' => 'Finlândia',
            'nacionalidade' => 'Finlandesa',
            'ddi' => '358',
        ],
        [
            'id' => '248',
            'nome' => 'Ilhas Aland',
            'nacionalidade' => 'Alandesa',
            'ddi' => null,
        ],
        [
            'id' => '250',
            'nome' => 'França',
            'nacionalidade' => 'Francesa',
            'ddi' => '33',
        ],
        [
            'id' => '254',
            'nome' => 'Guiana Francesa',
            'nacionalidade' => 'Franco Guianêsa',
            'ddi' => null,
        ],
        [
            'id' => '258',
            'nome' => 'Polinésia Francesa',
            'nacionalidade' => 'Polinésia',
            'ddi' => null,
        ],
        [
            'id' => '260',
            'nome' => 'Terras Austrais e Antárticas Francesas',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '262',
            'nome' => 'Djibouti',
            'nacionalidade' => 'Djibutiense',
            'ddi' => null,
        ],
        [
            'id' => '266',
            'nome' => 'Gabão',
            'nacionalidade' => 'Gabonesa',
            'ddi' => null,
        ],
        [
            'id' => '268',
            'nome' => 'Geórgia',
            'nacionalidade' => 'Georgiana',
            'ddi' => '995',
        ],
        [
            'id' => '270',
            'nome' => 'Gâmbia',
            'nacionalidade' => 'Gambiana',
            'ddi' => '220',
        ],
        [
            'id' => '275',
            'nome' => 'Palestina',
            'nacionalidade' => 'Palestina',
            'ddi' => '970',
        ],
        [
            'id' => '276',
            'nome' => 'Alemanha',
            'nacionalidade' => 'Alemã',
            'ddi' => '49',
        ],
        [
            'id' => '288',
            'nome' => 'Gana',
            'nacionalidade' => 'Ganesa',
            'ddi' => '233',
        ],
        [
            'id' => '292',
            'nome' => 'Gibraltar',
            'nacionalidade' => 'Gibraltina',
            'ddi' => '350',
        ],
        [
            'id' => '296',
            'nome' => 'Kiribati',
            'nacionalidade' => 'Quiribatiana',
            'ddi' => '686',
        ],
        [
            'id' => '300',
            'nome' => 'Grécia',
            'nacionalidade' => 'Grega',
            'ddi' => '30',
        ],
        [
            'id' => '304',
            'nome' => 'Groenlândia',
            'nacionalidade' => 'Groenlandesa',
            'ddi' => '299',
        ],
        [
            'id' => '308',
            'nome' => 'Granada',
            'nacionalidade' => 'Granadina',
            'ddi' => null,
        ],
        [
            'id' => '312',
            'nome' => 'Guadalupe',
            'nacionalidade' => 'Guadalupense',
            'ddi' => null,
        ],
        [
            'id' => '316',
            'nome' => 'Guam',
            'nacionalidade' => 'Guamesa',
            'ddi' => null,
        ],
        [
            'id' => '320',
            'nome' => 'Guatemala',
            'nacionalidade' => 'Guatemalteca',
            'ddi' => '502',
        ],
        [
            'id' => '324',
            'nome' => 'Guiné',
            'nacionalidade' => 'Guineana',
            'ddi' => null,
        ],
        [
            'id' => '328',
            'nome' => 'Guiana',
            'nacionalidade' => 'Guianense',
            'ddi' => '592',
        ],
        [
            'id' => '332',
            'nome' => 'Haiti',
            'nacionalidade' => 'Haitiana',
            'ddi' => null,
        ],
        [
            'id' => '334',
            'nome' => 'Ilha Heard e Ilhas McDonald',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '336',
            'nome' => 'Vaticano',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '339',
            'nome' => 'Apátrida',
            'nacionalidade' => 'Apatrida',
            'ddi' => null,
        ],
        [
            'id' => '340',
            'nome' => 'Honduras',
            'nacionalidade' => 'Hondurenha',
            'ddi' => '504',
        ],
        [
            'id' => '344',
            'nome' => 'Hong Kong',
            'nacionalidade' => 'Honconguesa',
            'ddi' => '852',
        ],
        [
            'id' => '348',
            'nome' => 'Hungria',
            'nacionalidade' => 'Húngara',
            'ddi' => '36',
        ],
        [
            'id' => '352',
            'nome' => 'Islândia',
            'nacionalidade' => 'Islandesa',
            'ddi' => '354',
        ],
        [
            'id' => '356',
            'nome' => 'Índia',
            'nacionalidade' => 'Indiana',
            'ddi' => null,
        ],
        [
            'id' => '360',
            'nome' => 'Indonésia',
            'nacionalidade' => 'Indonésia',
            'ddi' => '62',
        ],
        [
            'id' => '364',
            'nome' => 'Irã',
            'nacionalidade' => 'Iraniana',
            'ddi' => '98',
        ],
        [
            'id' => '368',
            'nome' => 'Iraque',
            'nacionalidade' => 'Iraquiana',
            'ddi' => '964',
        ],
        [
            'id' => '372',
            'nome' => 'Irlanda',
            'nacionalidade' => 'Irlandesa',
            'ddi' => null,
        ],
        [
            'id' => '376',
            'nome' => 'Israel',
            'nacionalidade' => 'Israelense',
            'ddi' => '972',
        ],
        [
            'id' => '380',
            'nome' => 'Itália',
            'nacionalidade' => 'Italiana',
            'ddi' => '39',
        ],
        [
            'id' => '384',
            'nome' => 'Costa do Marfim',
            'nacionalidade' => 'Marfiniana',
            'ddi' => '225',
        ],
        [
            'id' => '388',
            'nome' => 'Jamaica',
            'nacionalidade' => 'Jamaicana',
            'ddi' => null,
        ],
        [
            'id' => '392',
            'nome' => 'Japão',
            'nacionalidade' => 'Japonesa',
            'ddi' => '81',
        ],
        [
            'id' => '398',
            'nome' => 'Cazaquistão',
            'nacionalidade' => 'Cazaque',
            'ddi' => '7',
        ],
        [
            'id' => '400',
            'nome' => 'Jordânia',
            'nacionalidade' => 'Jordaniana',
            'ddi' => '962',
        ],
        [
            'id' => '404',
            'nome' => 'Quénia',
            'nacionalidade' => 'Queniana',
            'ddi' => null,
        ],
        [
            'id' => '408',
            'nome' => 'Coreia do Norte',
            'nacionalidade' => 'Norte-coreana',
            'ddi' => '850',
        ],
        [
            'id' => '410',
            'nome' => 'Coreia do Sul',
            'nacionalidade' => 'Sul-Coreana',
            'ddi' => null,
        ],
        [
            'id' => '414',
            'nome' => 'Kuwait',
            'nacionalidade' => 'Kuwaitiana',
            'ddi' => null,
        ],
        [
            'id' => '417',
            'nome' => 'República Quirguiz',
            'nacionalidade' => 'Quirguiz',
            'ddi' => null,
        ],
        [
            'id' => '418',
            'nome' => 'Laos',
            'nacionalidade' => 'Laociana',
            'ddi' => '856',
        ],
        [
            'id' => '422',
            'nome' => 'Líbano',
            'nacionalidade' => 'Libanesa',
            'ddi' => '961',
        ],
        [
            'id' => '426',
            'nome' => 'Lesoto',
            'nacionalidade' => 'Lesotiana',
            'ddi' => '266',
        ],
        [
            'id' => '428',
            'nome' => 'Letónia',
            'nacionalidade' => 'Letã',
            'ddi' => null,
        ],
        [
            'id' => '430',
            'nome' => 'Libéria',
            'nacionalidade' => 'Liberiana',
            'ddi' => '231',
        ],
        [
            'id' => '434',
            'nome' => 'Líbia',
            'nacionalidade' => 'Líbia',
            'ddi' => '218',
        ],
        [
            'id' => '438',
            'nome' => 'Liechtenstein',
            'nacionalidade' => 'Liechtensteinense',
            'ddi' => '423',
        ],
        [
            'id' => '440',
            'nome' => 'Lituânia',
            'nacionalidade' => 'Lituana',
            'ddi' => '370',
        ],
        [
            'id' => '442',
            'nome' => 'Luxemburgo',
            'nacionalidade' => 'Luxemburguesa',
            'ddi' => '352',
        ],
        [
            'id' => '446',
            'nome' => 'Macau',
            'nacionalidade' => 'Macaense',
            'ddi' => '853',
        ],
        [
            'id' => '450',
            'nome' => 'Madagáscar',
            'nacionalidade' => 'Malgaxe',
            'ddi' => null,
        ],
        [
            'id' => '454',
            'nome' => 'Malawi',
            'nacionalidade' => 'Malauiana',
            'ddi' => '265',
        ],
        [
            'id' => '458',
            'nome' => 'Malásia',
            'nacionalidade' => 'Malaia',
            'ddi' => '60',
        ],
        [
            'id' => '462',
            'nome' => 'Maldivas',
            'nacionalidade' => 'Maldívia',
            'ddi' => '960',
        ],
        [
            'id' => '466',
            'nome' => 'Mali',
            'nacionalidade' => 'Maliana',
            'ddi' => '223',
        ],
        [
            'id' => '470',
            'nome' => 'Malta',
            'nacionalidade' => 'Maltesa',
            'ddi' => null,
        ],
        [
            'id' => '474',
            'nome' => 'Martinica',
            'nacionalidade' => 'Martinicana',
            'ddi' => '596',
        ],
        [
            'id' => '478',
            'nome' => 'Mauritânia',
            'nacionalidade' => 'Mauritana',
            'ddi' => '222',
        ],
        [
            'id' => '480',
            'nome' => 'Maurícia',
            'nacionalidade' => 'Mauriciana',
            'ddi' => '230',
        ],
        [
            'id' => '484',
            'nome' => 'México',
            'nacionalidade' => 'Mexicana',
            'ddi' => '52',
        ],
        [
            'id' => '492',
            'nome' => 'Mônaco',
            'nacionalidade' => 'Monegasca',
            'ddi' => '377',
        ],
        [
            'id' => '496',
            'nome' => 'Mongólia',
            'nacionalidade' => 'Mongol',
            'ddi' => '976',
        ],
        [
            'id' => '498',
            'nome' => 'Moldávia',
            'nacionalidade' => 'Moldávia',
            'ddi' => null,
        ],
        [
            'id' => '499',
            'nome' => 'Montenegro',
            'nacionalidade' => 'Montenegrina',
            'ddi' => '382',
        ],
        [
            'id' => '500',
            'nome' => 'Montserrat',
            'nacionalidade' => 'Monserratense',
            'ddi' => null,
        ],
        [
            'id' => '504',
            'nome' => 'Marrocos',
            'nacionalidade' => 'Marroquina',
            'ddi' => '212',
        ],
        [
            'id' => '508',
            'nome' => 'Moçambique',
            'nacionalidade' => 'Moçambicana',
            'ddi' => '258',
        ],
        [
            'id' => '512',
            'nome' => 'Omã',
            'nacionalidade' => 'Omanense',
            'ddi' => null,
        ],
        [
            'id' => '516',
            'nome' => 'Namíbia',
            'nacionalidade' => 'Namibiana',
            'ddi' => '264',
        ],
        [
            'id' => '520',
            'nome' => 'Nauru',
            'nacionalidade' => 'Nauruense',
            'ddi' => '674',
        ],
        [
            'id' => '524',
            'nome' => 'Nepal',
            'nacionalidade' => 'Nepalesa',
            'ddi' => '977',
        ],
        [
            'id' => '528',
            'nome' => 'Holanda',
            'nacionalidade' => 'Holandesa',
            'ddi' => '31',
        ],
        [
            'id' => '530',
            'nome' => 'Antilhas Holandesas',
            'nacionalidade' => 'Antilhana',
            'ddi' => '599',
        ],
        [
            'id' => '531',
            'nome' => 'Curaçao',
            'nacionalidade' => 'Curacaunse',
            'ddi' => null,
        ],
        [
            'id' => '533',
            'nome' => 'Aruba',
            'nacionalidade' => 'Arubana',
            'ddi' => '297',
        ],
        [
            'id' => '534',
            'nome' => 'Sint Maarten (Parte Holandesa)',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '535',
            'nome' => 'Bonaire, Saint Eustatius E Saba',
            'nacionalidade' => 'Bonaire',
            'ddi' => null,
        ],
        [
            'id' => '540',
            'nome' => 'Nova Caledónia',
            'nacionalidade' => 'Neocaledônia',
            'ddi' => '687',
        ],
        [
            'id' => '548',
            'nome' => 'Vanuatu',
            'nacionalidade' => 'Vanuatense',
            'ddi' => '678',
        ],
        [
            'id' => '554',
            'nome' => 'Nova Zelândia',
            'nacionalidade' => 'Neozelandesa',
            'ddi' => '64',
        ],
        [
            'id' => '558',
            'nome' => 'Nicarágua',
            'nacionalidade' => 'Nicaraguense',
            'ddi' => '505',
        ],
        [
            'id' => '562',
            'nome' => 'Níger',
            'nacionalidade' => 'Nigerina',
            'ddi' => null,
        ],
        [
            'id' => '566',
            'nome' => 'Nigéria',
            'nacionalidade' => 'Nigeriana',
            'ddi' => '234',
        ],
        [
            'id' => '570',
            'nome' => 'Niue',
            'nacionalidade' => 'Niuense',
            'ddi' => '683',
        ],
        [
            'id' => '574',
            'nome' => 'Ilha Norfolk',
            'nacionalidade' => 'Norfolquiana',
            'ddi' => '672',
        ],
        [
            'id' => '578',
            'nome' => 'Noruega',
            'nacionalidade' => 'Norueguesa',
            'ddi' => '47',
        ],
        [
            'id' => '580',
            'nome' => 'Ilhas Marianas do Norte',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '581',
            'nome' => 'Ilhas Menores Distantes dos Estados Unidos',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '583',
            'nome' => 'Estados Federados da Micronésia',
            'nacionalidade' => 'Micronésia',
            'ddi' => '691',
        ],
        [
            'id' => '584',
            'nome' => 'Ilhas Marshall',
            'nacionalidade' => 'Marshallina',
            'ddi' => '692',
        ],
        [
            'id' => '585',
            'nome' => 'Palau',
            'nacionalidade' => 'Palauense',
            'ddi' => '680',
        ],
        [
            'id' => '586',
            'nome' => 'Paquistão',
            'nacionalidade' => 'Paquistanesa',
            'ddi' => '92',
        ],
        [
            'id' => '591',
            'nome' => 'Panamá',
            'nacionalidade' => 'Panamense',
            'ddi' => '507',
        ],
        [
            'id' => '598',
            'nome' => 'Papua-Nova Guiné',
            'nacionalidade' => 'Papua',
            'ddi' => null,
        ],
        [
            'id' => '600',
            'nome' => 'Paraguai',
            'nacionalidade' => 'Paraguaia',
            'ddi' => '595',
        ],
        [
            'id' => '604',
            'nome' => 'Peru',
            'nacionalidade' => 'Peruana',
            'ddi' => '51',
        ],
        [
            'id' => '608',
            'nome' => 'Filipinas',
            'nacionalidade' => 'Filipina',
            'ddi' => '63',
        ],
        [
            'id' => '612',
            'nome' => 'Ilhas Pitcairn',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '616',
            'nome' => 'Polônia',
            'nacionalidade' => 'Polonesa',
            'ddi' => '48',
        ],
        [
            'id' => '620',
            'nome' => 'Portugal',
            'nacionalidade' => 'Portuguesa',
            'ddi' => '351',
        ],
        [
            'id' => '624',
            'nome' => 'Guiné-Bissau',
            'nacionalidade' => 'Guineense',
            'ddi' => null,
        ],
        [
            'id' => '626',
            'nome' => 'Timor-Leste',
            'nacionalidade' => 'Timorense',
            'ddi' => null,
        ],
        [
            'id' => '630',
            'nome' => 'Porto Rico',
            'nacionalidade' => 'Porto-riquenha',
            'ddi' => null,
        ],
        [
            'id' => '634',
            'nome' => 'Catar',
            'nacionalidade' => 'Catariana',
            'ddi' => '974',
        ],
        [
            'id' => '638',
            'nome' => 'Réunion',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '642',
            'nome' => 'Roménia',
            'nacionalidade' => 'Romena',
            'ddi' => null,
        ],
        [
            'id' => '643',
            'nome' => 'Rússia',
            'nacionalidade' => 'Russa',
            'ddi' => '7',
        ],
        [
            'id' => '646',
            'nome' => 'Ruanda',
            'nacionalidade' => 'Ruandesa',
            'ddi' => '250',
        ],
        [
            'id' => '652',
            'nome' => 'São Bartolomeu',
            'nacionalidade' => 'São-Bartolomense',
            'ddi' => null,
        ],
        [
            'id' => '654',
            'nome' => 'Santa Helena',
            'nacionalidade' => 'Santa-helenense',
            'ddi' => '290',
        ],
        [
            'id' => '659',
            'nome' => 'São Cristóvão e Nevis',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '660',
            'nome' => 'Anguilla',
            'nacionalidade' => 'Anguilana',
            'ddi' => null,
        ],
        [
            'id' => '662',
            'nome' => 'Santa Lúcia',
            'nacionalidade' => 'Santa-lucense',
            'ddi' => null,
        ],
        [
            'id' => '663',
            'nome' => 'Saint-Martin (Parte Francesa)',
            'nacionalidade' => 'São-Martinhense',
            'ddi' => null,
        ],
        [
            'id' => '666',
            'nome' => 'São Pedro e Miquelão',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '670',
            'nome' => 'São Vicente e Granadinas',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '674',
            'nome' => 'San Marino',
            'nacionalidade' => 'São-marinhense',
            'ddi' => '378',
        ],
        [
            'id' => '678',
            'nome' => 'São Tomé e Príncipe',
            'nacionalidade' => 'Santomense',
            'ddi' => '239',
        ],
        [
            'id' => '680',
            'nome' => 'Sark',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '682',
            'nome' => 'Arábia Saudita',
            'nacionalidade' => 'Saudita',
            'ddi' => '966',
        ],
        [
            'id' => '686',
            'nome' => 'Senegal',
            'nacionalidade' => 'Senegalesa',
            'ddi' => '221',
        ],
        [
            'id' => '688',
            'nome' => 'Sérvia',
            'nacionalidade' => 'Sérvia',
            'ddi' => '381',
        ],
        [
            'id' => '690',
            'nome' => 'Seicheles',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '694',
            'nome' => 'Serra Leoa',
            'nacionalidade' => 'Serra-leonesa',
            'ddi' => '232',
        ],
        [
            'id' => '702',
            'nome' => 'Cingapura',
            'nacionalidade' => 'Cingapurense',
            'ddi' => null,
        ],
        [
            'id' => '703',
            'nome' => 'Eslováquia',
            'nacionalidade' => 'Eslovaca',
            'ddi' => '421',
        ],
        [
            'id' => '704',
            'nome' => 'Vietnã',
            'nacionalidade' => 'Vietnamita',
            'ddi' => null,
        ],
        [
            'id' => '705',
            'nome' => 'Eslovênia',
            'nacionalidade' => 'Eslovena',
            'ddi' => '386',
        ],
        [
            'id' => '706',
            'nome' => 'Somália',
            'nacionalidade' => 'Somali',
            'ddi' => null,
        ],
        [
            'id' => '710',
            'nome' => 'África do Sul',
            'nacionalidade' => 'Sul-africana',
            'ddi' => '27',
        ],
        [
            'id' => '716',
            'nome' => 'Zimbábue',
            'nacionalidade' => 'Zimbabuana',
            'ddi' => null,
        ],
        [
            'id' => '724',
            'nome' => 'Espanha',
            'nacionalidade' => 'Espanhola',
            'ddi' => '34',
        ],
        [
            'id' => '728',
            'nome' => 'Sudão Do Sul',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '729',
            'nome' => 'Sudão',
            'nacionalidade' => 'Sudanesa',
            'ddi' => null,
        ],
        [
            'id' => '732',
            'nome' => 'Saara Ocidental',
            'nacionalidade' => 'Saráui',
            'ddi' => '212',
        ],
        [
            'id' => '740',
            'nome' => 'Suriname',
            'nacionalidade' => 'Surinamense',
            'ddi' => '597',
        ],
        [
            'id' => '744',
            'nome' => 'Svalbard and Jan Mayen',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '748',
            'nome' => 'Suazilândia',
            'nacionalidade' => 'Suazilandesa',
            'ddi' => '268',
        ],
        [
            'id' => '752',
            'nome' => 'Suécia',
            'nacionalidade' => 'Sueca',
            'ddi' => '46',
        ],
        [
            'id' => '756',
            'nome' => 'Suíça',
            'nacionalidade' => 'Suíça',
            'ddi' => '41',
        ],
        [
            'id' => '760',
            'nome' => 'Síria',
            'nacionalidade' => 'Síria',
            'ddi' => '963',
        ],
        [
            'id' => '762',
            'nome' => 'Tajiquistão',
            'nacionalidade' => 'Tajique',
            'ddi' => null,
        ],
        [
            'id' => '764',
            'nome' => 'Tailândia',
            'nacionalidade' => 'Tailandesa',
            'ddi' => '66',
        ],
        [
            'id' => '768',
            'nome' => 'Togo',
            'nacionalidade' => 'Togolesa',
            'ddi' => '228',
        ],
        [
            'id' => '772',
            'nome' => 'Tokelau',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '776',
            'nome' => 'Tonga',
            'nacionalidade' => 'Tonganesa',
            'ddi' => '676',
        ],
        [
            'id' => '780',
            'nome' => 'Trinidad e Tobago',
            'nacionalidade' => 'Trinitina',
            'ddi' => null,
        ],
        [
            'id' => '784',
            'nome' => 'Emirados Árabes Unidos',
            'nacionalidade' => 'Emiriana',
            'ddi' => '971',
        ],
        [
            'id' => '788',
            'nome' => 'Tunísia',
            'nacionalidade' => 'Tunisiana',
            'ddi' => '216',
        ],
        [
            'id' => '792',
            'nome' => 'Turquia',
            'nacionalidade' => 'Turca',
            'ddi' => '90',
        ],
        [
            'id' => '795',
            'nome' => 'Turcomenistão',
            'nacionalidade' => 'Turcomena',
            'ddi' => '993',
        ],
        [
            'id' => '796',
            'nome' => 'Turks e Caicos',
            'nacionalidade' => 'Turco-caicense',
            'ddi' => null,
        ],
        [
            'id' => '798',
            'nome' => 'Tuvalu',
            'nacionalidade' => 'Tuvaluana',
            'ddi' => '688',
        ],
        [
            'id' => '800',
            'nome' => 'Uganda',
            'nacionalidade' => 'Ugandesa',
            'ddi' => '256',
        ],
        [
            'id' => '804',
            'nome' => 'Ucrânia',
            'nacionalidade' => 'Ucraniana',
            'ddi' => '380',
        ],
        [
            'id' => '807',
            'nome' => 'Macedônia',
            'nacionalidade' => 'Macedônica',
            'ddi' => null,
        ],
        [
            'id' => '818',
            'nome' => 'Egito',
            'nacionalidade' => 'Egipcia',
            'ddi' => null,
        ],
        [
            'id' => '826',
            'nome' => 'Reino Unido',
            'nacionalidade' => 'Britânica',
            'ddi' => null,
        ],
        [
            'id' => '830',
            'nome' => 'Ilhas Do Canal',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '831',
            'nome' => 'Guernsey',
            'nacionalidade' => 'Guernesiana',
            'ddi' => '44',
        ],
        [
            'id' => '832',
            'nome' => 'Jersey',
            'nacionalidade' => 'Jersiana',
            'ddi' => '44',
        ],
        [
            'id' => '833',
            'nome' => 'Ilha de Man',
            'nacionalidade' => 'Manesa',
            'ddi' => '44',
        ],
        [
            'id' => '834',
            'nome' => 'Tanzânia',
            'nacionalidade' => 'Tanzaniana',
            'ddi' => '255',
        ],
        [
            'id' => '840',
            'nome' => 'Estados Unidos',
            'nacionalidade' => 'Norte-Americana',
            'ddi' => null,
        ],
        [
            'id' => '850',
            'nome' => 'Ilhas Virgens Americanas',
            'nacionalidade' => null,
            'ddi' => null,
        ],
        [
            'id' => '854',
            'nome' => 'Burkina Faso',
            'nacionalidade' => 'Burquinense',
            'ddi' => '226',
        ],
        [
            'id' => '858',
            'nome' => 'Uruguai',
            'nacionalidade' => 'Uruguaia',
            'ddi' => '598',
        ],
        [
            'id' => '860',
            'nome' => 'Uzbequistão',
            'nacionalidade' => 'Uzbeque',
            'ddi' => '998',
        ],
        [
            'id' => '862',
            'nome' => 'Venezuela',
            'nacionalidade' => 'Venezuelana',
            'ddi' => '58',
        ],
        [
            'id' => '876',
            'nome' => 'Wallis e Futuna',
            'nacionalidade' => 'Wallis-futunense',
            'ddi' => '681',
        ],
        [
            'id' => '882',
            'nome' => 'Samoa',
            'nacionalidade' => 'Samoana',
            'ddi' => null,
        ],
        [
            'id' => '887',
            'nome' => 'Iémen',
            'nacionalidade' => 'Iemenita',
            'ddi' => null,
        ],
        [
            'id' => '894',
            'nome' => 'Zâmbia',
            'nacionalidade' => 'Zambiana',
            'ddi' => '260',
        ],
        [
            'id' => '999',
            'nome' => 'Outra Nacionalidade',
            'nacionalidade' => null,
            'ddi' => null,
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pais::insertOrIgnore($this->paises);
    }
}
